/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        this.setLocation(300, 200);
        File file = new File("luumk.txt");

        // if file doesnt exists, then create it
        String tendangnhap = "", matkhau = "";

        FileReader fw;
        try {
            fw = new FileReader(file);
            BufferedReader bw = new BufferedReader(fw);
            try {
                tendangnhap = bw.readLine();
                matkhau = bw.readLine();
                bw.close();
            } catch (IOException ex) {
            }

        } catch (FileNotFoundException ex) {
            System.out.println("không tìm thấy file lưu mk");
        }

        TaiKhoan150.setText(tendangnhap);
        Pass150.setText(matkhau);
        if (!tendangnhap.equals("")) {
            NhoMatKhau150.setSelected(rootPaneCheckingEnabled);
            System.out.println("checked lưu mật khẩu");
        } else {
            System.out.println("đã bỏ checkbox lưu mật khẩu\n\n");
        }
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public static int quyen = 0;
    public static String ten = "", user = "";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Pass150 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TaiKhoan150 = new javax.swing.JTextField();
        NhoMatKhau150 = new javax.swing.JCheckBox();
        DangKy150 = new javax.swing.JButton();
        DangNhap150 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Pass150, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 180, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Uy tín tạo nên thương hiệu!");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hệ Thống Quản Lí BlueCenTer");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 370, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Vui Lòng Nhập Thông Tin !!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐĂNG NHẬP HỆ THỐNG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tài Khoản :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 100, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mật Khẩu :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, 30));

        TaiKhoan150.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(TaiKhoan150, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 180, -1));

        NhoMatKhau150.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        NhoMatKhau150.setForeground(new java.awt.Color(0, 204, 204));
        NhoMatKhau150.setText("Nhớ Mật Khẩu");
        NhoMatKhau150.setName(""); // NOI18N
        jPanel1.add(NhoMatKhau150, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 150, -1));

        DangKy150.setBackground(new java.awt.Color(204, 255, 204));
        DangKy150.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DangKy150.setForeground(new java.awt.Color(0, 153, 153));
        DangKy150.setText("Đăng Ký");
        DangKy150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangKy150ActionPerformed(evt);
            }
        });
        jPanel1.add(DangKy150, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));
        DangKy150.getAccessibleContext().setAccessibleName("DangKy");

        DangNhap150.setBackground(new java.awt.Color(204, 255, 204));
        DangNhap150.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DangNhap150.setForeground(new java.awt.Color(0, 153, 153));
        DangNhap150.setText("Đăng Nhập");
        DangNhap150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangNhap150ActionPerformed(evt);
            }
        });
        jPanel1.add(DangNhap150, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, -1));
        DangNhap150.getAccessibleContext().setAccessibleName("DangNhap");

        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 0, -1, 254));

        jLabel7.setBackground(new java.awt.Color(0, 0, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nen.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 1000, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DangKy150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangKy150ActionPerformed
        // TODO add your handling code here:
        DangKy l = new DangKy();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DangKy150ActionPerformed

    private void DangNhap150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangNhap150ActionPerformed
        // TODO add your handling code here:
        String strUsername = TaiKhoan150.getText().trim();
        String strPassword = String.valueOf(Pass150.getPassword()).trim();

        String cautruyvan = "select * from Users where TenDangNhap= '" + strUsername + "' and Password= '" + strPassword + "'";
        ResultSet rs = Main.main.connection.ExcuteQueryGetTable(cautruyvan);
        String luumk = "", luutdn = "";
        if (NhoMatKhau150.isSelected()) {
            luutdn = strUsername;
            luumk = strPassword;
            System.out.println("lưu mật khẩu");
        } else {
            luutdn = "";
            luumk = "";
            System.out.println("không lưu mật khẩu");
        }
        try {
            File file = new File("luumk.txt");
            if (!file.exists()) {
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(luutdn + "\n" + luumk);
            bw.close();
            if (NhoMatKhau150.isSelected()) {
                System.out.println("lưu phiên đăng nhập thành công");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        if (KiemTra(strUsername, strPassword)) {

            Main.main.frmTC.show();
            this.dispose();
        } else {
            ThongBao("Bạn nhập sai tài khoản hoặc mật khẩu", "Lỗi đăng nhập", 2);
        }
    }//GEN-LAST:event_DangNhap150ActionPerformed
    private boolean KiemTra(String tdn, String mk) {
        boolean kq = false;

        String cautruyvan = "select * from Users where TenDangNhap= '" + tdn + "' and Password= '" + mk + "'";
        System.out.println(cautruyvan);
        ResultSet rs = Main.main.connection.ExcuteQueryGetTable(cautruyvan);

        try {
            if (rs.next()) {
                kq = true;
                quyen = rs.getInt("Quyen");
                ten = rs.getString("TenNhanVien");
                user = rs.getString("UserName");
                System.out.println(" " + quyen);
            }
        } catch (SQLException ex) {
            System.out.println("lỗi đăng nhập");
        }

        return kq;
    }

    private boolean KiemTraChuaChuVaSo(String chuoiCanKiemTra) {
        boolean ketQua = false;
        Pattern p = Pattern.compile(".*[a-zA-Z].*");
        Matcher m = p.matcher(chuoiCanKiemTra);
        if (!(chuoiCanKiemTra == chuoiCanKiemTra.toLowerCase())) {
            ketQua = m.find();
        }
        return ketQua;
    }

    public static void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) {
        JOptionPane.showMessageDialog(new JFrame(), noiDungThongBao,
                tieuDeThongBao, icon);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DangKy150;
    private javax.swing.JButton DangNhap150;
    private javax.swing.JCheckBox NhoMatKhau150;
    private javax.swing.JPasswordField Pass150;
    private javax.swing.JTextField TaiKhoan150;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
